mirror_repo: AbdullahSharif/repo_for_gh_app_test
mirror_file_path: from-repo-a.md  # the path where you want to create a new file in repo B. (OPTIONAL)
base_branch: master # from which the new branch needs to be checked out. (OPTIONAL, if not mentioned, it will use "main" by default.)
